### PR TITLE
Subjectnumber2394/merge moving platforms into recent code

### LINKED ISSUE #17: Moving Platforms
I've noticed three issues:
1) The player can stick to the side of the platform they try to move in the opposite direction the platform is moving.
2)The player does not interact will walls while on the platform (not 100% sure if important depending on level design).
3)The player can stick to the bottom of the platform. I've only been able to check this for a descending platform though. If you don't hold jump after sticking, the player is shot down.

platbug
platbugii
platbugiii

### PR DESCRIPTION
**Pull request by SubjectNumber2394**
Closes #17

### CODE REVIEW

**Comment by sb7766** [comment]
Does this fix the issues mentioned in #17?

**Comment by SubjectNumber2394** [comment]
Yes, this fixes those 3 issues

**Comment by sb7766** [comment]
Alright. Go ahead and put Closes #17 in the description of the PR. Also would you like me to handle the conflicts or did you plan on doing it?

**Comment by SubjectNumber2394** [comment]
I haven't merged before so it might be better for you to do it for now.

**Review by sb7766 — APPROVED** [review]
Looks good, but you'll need to change the object to meet the new 24x24 standard.

**Pull request merged**
